default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stellar_dev

test:
  <<: *default
  database: stellar_test

production:
  <<: *default
  database: stellar_production
  username: stellar
  password: <%= ENV['STELLAR_DATABASE_PASSWORD'] %>
